### ISSUE TITLE
Missing templates file ssh_config and inventory

### ISSUE THREAD

**Issue by asias** [michoecho/scylla-cluster-test-scripts#1]
It looks like the template files are not committed in the repo.  The templates ssh_config and inventory are missing. 
```
Traceback (most recent call last):
  File "/home/asias/src/cloudius-systems/scylla-cluster-test-scripts/prov/provision-terraform", line 24, in <module>
    terraform.apply(deployment_name, terraform_plan, config)
  File "/home/asias/src/cloudius-systems/scylla-cluster-test-scripts/prov/terraform.py", line 46, in apply
    ssh_template = jinja_env.get_template("ssh_config")
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/jinja2/environment.py", line 1013, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/jinja2/environment.py", line 972, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ssh_config
```

**Comment by michoecho** [comment]
True, I forgot to add them.

I pushed an updated checkpoint of the scripts to `master`.

Fixed by 74e6520f75e11d9a21dd897eeef6d3d5a59551a2
